# Generated by Django 3.2.7 on 2021-09-26 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('diocese', models.CharField(max_length=50)),
                ('church', models.CharField(max_length=100)),
                ('father_of_confession', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=11)),
                ('qualification', models.CharField(max_length=100)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.CharField(choices=[('دبلومة العلوم اللاهوتية', 'دبلومة العلوم اللاهوتية'), ('بكالوريوس العلوم اللاهوتية', 'بكالوريوس العلوم اللاهوتية'), ('كورسات متخصصة', 'كورسات متخصصة'), ('دراسات عليا', 'دراسات عليا')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
