# Generated by Django 3.2.7 on 2021-09-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dar_El_Nashr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dibloma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=15)),
                ('Description', models.TextField()),
                ('Link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Magazin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialized_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Who_We_Are',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
    ]
