# Generated by Django 3.2.7 on 2021-09-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Pic', models.ImageField(upload_to='media/')),
                ('Test', models.CharField(blank=True, max_length=300, null=True)),
                ('Slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Video', models.CharField(max_length=300)),
                ('More_Info', models.TextField()),
                ('Audio_Lecture', models.CharField(blank=True, max_length=300, null=True)),
                ('Lecture_Files', models.CharField(blank=True, max_length=300, null=True)),
                ('Sheet', models.CharField(blank=True, max_length=300, null=True)),
                ('Test', models.CharField(blank=True, max_length=300, null=True)),
                ('Slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialized_Courses.subject')),
            ],
        ),
    ]
