# Generated by Django 3.2.7 on 2021-09-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graduates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Graduates.year'),
            preserve_default=False,
        ),
    ]
