# Generated by Django 3.2.7 on 2021-09-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graduates', '0002_students_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
