# Generated by Django 3.2.7 on 2021-09-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graduates', '0003_students_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Slug',
        ),
    ]
