# Generated by Django 3.2.7 on 2021-09-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_and_Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
            ],
        ),
    ]
